import 'package:get/get.dart';

class LocalClass extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "AllDrugsAPT": "في المستودع",
          "CartScreeAPT": "السلة",
          "Order": "الطلبية",
          "Your cart is empty!": "سلة المشتريات فارغة",
          "Fill it!": "هيا ابدأ بالتسوق",
          "Categories": "التصنيفات",
          "Companies": "الشركات",
          "There is no drugs in this category": "لا يوجد ادوية في هذا التصنيف",
          "There is no drugs in this company": " لا يوجد ادوية في هذه الشركة",
          "Trade Name:": "الاسم التجاري",
          "Generic Name:": "الاسم العلمي",
          "Category:": "التصنيف",
          "Company:": "الشركة",
          "unit": "قطعة",
          "Amount:": "الكمية",
          "Expiring Date:": "تاريخ انتهاء الصلاحية",
          "You can\'t edit quantity from the cart": "لا تستطسع تعديل الكمية من السلة",
          "amount": "الكمية",
          "negative qunatity": "لا يمكن اضافة كمية سالبة من الدواء",
          "Rel": "؟حقا",
          "Add to cart": "إضافة",
          "Quantity have letter!?": "الكميات فيها احرف",
          "please enter only numbers": "رجاء ادخل فقط ارقام",
          "error": "خطأ",
          "no": "لا",
          "Why?": "لماذا ",
          "Add Some first": "أضف أدوية أولا",
          "Recent Categories": "أخر التصنيفات",
          "Recent Companies": " اخر الشركات",
          "see more": "المزيد",
          "Recent In Stock": "المضافة مؤخراً",
          "Login": "تسجيل الدخول",
          "Welcome back": "مرحبا بعودتك",
          "Of course you didn't forget your account information, doctor!": "بالتأكيد لم تنس معلومات حسابك ,دكتورنا",
          "Phone Number": "رقم الهاتف",
          "Password": "كلمة المرور",
          "Enter a strong password": "ادخل كلمة المرور",
          "Don\'t have an account?": "أليس لديك حساب",
          "Register.": "انشاء حساب",
          "Your Bill": "فاتورتك",
          "trade name": "السم التجاري",
          "price": "السعر",
          "My Orders": "طلباتي",
          "You haven't placed any order... yet!": "لم تضع اي طلبات.... بعد",
          "Make some orders": "اطلب الان",
          "Register": "انشاء حساب",
          "Create your new account": "أنشئ حساب جديد",
          "Hi doctor, Please enter your details to start makeing some orders.": "مرحبا دكتور ,رجاء أدخل معلوماتك لتبدأ طلبياتك",
          "First Name": "الاسم الاول",
          "Enter your first name": "ادخل اسمك الأول",
          "Last Name": "الكنية",
          "Enter your last name": "أدخل الكنية",
          "Already a member?": "هل لديك حساب",
          "Login.": "تسجيل الدخول",
          "Search": "ابحث...",
          "Search Results": "نتائج البحث",
          "no results": "لا يوجد نتائج",
          "Hi, doctor": "مرحباً، دكتور",
          "Quantity:": "الكمية:",
          "Delete!": "حذف",
          "orderSnack": "تم",
          "orderSnackM": "تم ارسال الطلبية بنجاح",
          "want to delete this order?": "هل تريد حذف الطلبية؟",
          "Cancel": "الغاء",
          "Delete": "حذف",
          "orderB": "اطلب الآن",
          "Already in cart": "تم إضافتها للسلة مسبقاً",
          "genericname": "الاسم العلمي",
          "Category": "التصنيف",
          "- Order Status:": "حالة الطلب",
          "Sent": "تم الارسال",
          "Preparing...": "قيد التحضير",
          "Recevied": "تم الاستلام",
          "SoldOut": "لقد انتهت كمية هذا الدواء",
          "- Payment Status:": "حالة الدفع",
          "Paid": "تم الدفع",
          "Unpaid": "غير مدفوع",
          "too far": "الكمية غير متاحة",
          "enoght amount": "لا يوجد لدى المستوع هذه الكمية من الدواء",
          "settings": "الاعدادات",
          "change language": "تغيير اللغة:",
          "English": "الانكليزية",
          "Arabic": "العربية",
          "Logout": "تسجيل الخروج",
          "The phone number must be numbers only": "الهاتف يجب ان يحوي ارقام فقط",
          "you should enter ten digits": "عليك ادخال عشر خانات",
        },
        "en": {
          "you should enter ten digits": "you should enter ten digits",
          "The phone number must be numbers only": "The phone number must be numbers only",
          "AllDrugsAPT": "In Stock",
          "CartScreeAPT": "My Cart",
          "Order": "Order",
          "SoldOut": "This drug hes been sold out",
          "Your cart is empty!": "Your cart is empty!",
          "Fill it!": "Fill it!",
          "Categories": "Categories",
          "Companies": "Companies",
          "There is no drugs in this category": "There is no drugs in this category",
          "There is no drugs in this company": "There is no drugs in this company",
          "Trade Name:": "Trade Name:",
          "Generic Name:": "Generic Name:",
          "Category:": "Category:",
          "Company:": "Company:",
          "unit": "unit",
          "Amount:": "Amount",
          "orderSnackM": "Order has been sent",
          "Expiring Date:": "Expiring Date:",
          "You can\'t edit quantity from the cart": "You can't edit quantity from the cart",
          "amount": "Amount",
          "negative qunatity": "you want to order a negative qunatity",
          "Rel": "Really?",
          "Add to cart": "Add",
          "Quantity have letter!?": "Quantity have letter!?",
          "please enter only numbers": "please enter only numbers",
          "no": "no",
          "orderB": "Order Now",
          "orderSnack": "Done",
          "Why?": "Why?",
          "Add Some first": "Add Some first",
          "Recent Categories": "Recent Categories",
          "Recent Companies": "Recent Companies",
          "Recent In Stock": "Recent In Stock",
          "Login": "Login",
          "Of course you didn't forget your account information, doctor!": "Of course you didn't forget your account information, doctor!",
          "Phone Number": "Phone Number",
          "Enter your phone number": "Enter your phone number",
          "Password": "Password",
          "Enter a strong password": "Enter a strong password",
          "Don\'t have an account?": "Don't have an account?",
          "Register.": "Register",
          "Your Bill": "Your Bill",
          "trade name": "trade name",
          "price": "price",
          "My Orders": "My Orders",
          "You haven't placed any order... yet!": "You haven't placed any order... yet!",
          "Make some orders": "Make some orders",
          "Register": "Register",
          "Create your new account": "Create your new account",
          "Hi doctor, Please enter your details to start makeing some orders.": "Hi doctor, Please enter your details to start makeing some orders.",
          "First Name": "First Name",
          "Enter your first name": "Enter your first name",
          "Last Name": "Last Name",
          "Enter your last name": "Enter your last name",
          "Already a member?": "Already a member?",
          "Already in cart": "Already in the cart",
          "Login.": "Login.",
          "Search": "Search...",
          "Search Results": "Search Results",
          "no results": "no results",
          "Hi, doctor": "Hi, doctor",
          "Quantity:": "Quantity:",
          "Delete!": "Delete!",
          "want to delete this order?": "want to delete this order?",
          "Cancel": "Cancel",
          "Delete": "Delete",
          "genericname": "generic name",
          "Category": "Category",
          "- Order Status:": "- Order Status:",
          "Sent": "Sent",
          "Preparing...": "Preparing...",
          "Recevied": "Recevied ✔",
          '- Payment Status:': "- Payment Status:",
          "Paid": "Paid ✔",
          "Unpaid": "Unpaid",
          "too far": "You went too far!",
          "enoght amount": "warehous doesn\'t have this amount",
          "settings": "Settings",
          "change language": "Change language:",
          "English": "English",
          "Arabic": "Arabic",
          "Logout": "Logout",
        }
      };
}
